name: Publish ğŸ¦†duckdb_extension_delta ğŸğŸ“¦ to PyPI

on:
  push:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_delta/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-delta-to-pypi.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_delta/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-delta-to-pypi.yml'

jobs:
  publish:
    uses: ./.github/workflows/_extension-publish.yml
    with:
      extension_name: delta
    secrets: inherit
