name: Publish ğŸ¦†duckdb_extension_spatial ğŸğŸ“¦ to PyPI

on:
  push:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_spatial/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-spatial-to-pypi.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_spatial/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-spatial-to-pypi.yml'

jobs:
  publish:
    uses: ./.github/workflows/_extension-publish.yml
    with:
      extension_name: spatial
    secrets: inherit
