name: Publish ğŸ¦†duckdb_extension_mysql ğŸğŸ“¦ to PyPI

on:
  push:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_mysql/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-mysql-to-pypi.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_mysql/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-mysql-to-pypi.yml'

jobs:
  publish:
    uses: ./.github/workflows/_extension-publish.yml
    with:
      extension_name: mysql
    secrets: inherit
