name: Publish ü¶Üduckdb_extension_sqlite_scanner üêçüì¶ to PyPI
on:
  push:
    branches:
      - main
      - support_*
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - support_*

concurrency:
  group: publish-sqlite_scanner-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build duckdb_extension_sqlite_scanner üì¶
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Act dependencies
      if: ${{ env.ACT }}
      run: |
        apt-get update && apt-get install sudo -y
    - name: Install uv
      run: |
        sudo apt update
        sudo apt install -y curl unzip
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install python
      run: uv venv --python 3.12
    - name: build duckdb_extension_sqlite_scanner for osx_arm64
      working-directory: ./extensions/duckdb_extension_sqlite_scanner
      run: |
        uv tool run hatch build -t wheel osx_arm64
    - name: build duckdb_extension_sqlite_scanner for linux_amd64
      working-directory: ./extensions/duckdb_extension_sqlite_scanner
      run: |
        uv tool run hatch build -t wheel linux_amd64
    - name: build duckdb_extension_sqlite_scanner for linux_arm64
      working-directory: ./extensions/duckdb_extension_sqlite_scanner
      run: |
        uv tool run hatch build -t wheel linux_arm64
    - name: build duckdb_extension_sqlite_scanner for osx_amd64
      working-directory: ./extensions/duckdb_extension_sqlite_scanner
      run: |
        uv tool run hatch build -t wheel osx_amd64
    - name: build duckdb_extension_sqlite_scanner for windows_amd64
      working-directory: ./extensions/duckdb_extension_sqlite_scanner
      run: |
        uv tool run hatch build -t wheel windows_amd64
    - name: Copy wheels to dist directory
      run: |
        mkdir dist
        cp extensions/*/*/*.whl dist
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: duckdb-extension-sqlite_scanner-distributions
        path: dist/*.whl
  test:
    needs:
      - build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - macos-15
          - macos-26
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y
      - name: Install curl
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y curl
      - name: Install uv via curl
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install uv via powershell
        if: runner.os == 'Windows'
        run: powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
      - name: Install python
        run: uv venv --python 3.12
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: duckdb-extension-sqlite_scanner-distributions
          path: dist/
      - name: Install packages
        env:
          EXTENSION_NAME: sqlite_scanner
        run: |
          uv pip install -e .
          uv pip install pytest
          uv pip install --no-index --find-links dist duckdb-extension-sqlite_scanner
          uv run pytest
  publish-to-pypi:
    name: Publish ü¶Üduckdb_extension_sqlite_scanner üêçüì¶ to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/duckdb-extension-sqlite_scanner

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: duckdb-extension-sqlite_scanner-distributions
          path: dist/
      - name: Publish distribution üì¶ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
